title = "Sabyasachi Bhattacharya"
baseURL = "https://njoysubho.github.io"
languageCode = "en-us"
theme = "ananke"

staticDir = ["static"]
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
publishDir = "public"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  favicon = ""
  description = "Java|Spring and More"
  facebook = ""
  twitter = "https://twitter.com/sabz2301"
  instagram = ""
  youtube = ""
  github = "https://github.com/njoysubho"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/sabyasachi-bhattacharya-a0283950/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
